# SPDX-FileCopyrightText: : 2022 Tom Brown
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: whobs-server
channels:
  - conda-forge
dependencies:
  - pip
  - pypsa>=0.18
  - atlite=0.0.2
  - yaml
  - numpy
  - pandas
  - xarray
  - netcdf4
  - networkx
  - scipy
  - shapely
  - pyomo
  - matplotlib
  - flask
  - redis
  - redis-py
  - rq
  - ipython
